// Answer 0

#[test]
fn test_retry_quadratic_error_new() {
    let error = RetryQuadraticError::new();
}

#[test]
fn test_retry_quadratic_error_instance() {
    let error = RetryQuadraticError::new();
}

